<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsMap\Mapping\AreaInterface'     => __DIR__ . '/src/Mapping/AreaInterface.php',
    'CmsMap\Mapping\MapInterface'      => __DIR__ . '/src/Mapping/MapInterface.php',
    'CmsMap\Mapping\MappableInterface' => __DIR__ . '/src/Mapping/MappableInterface.php',
    'CmsMap\Module'                    => __DIR__ . '/src/Module.php',
);
